### PR TITLE
First draft of CAP0005

### PR DESCRIPTION
**Pull request by MonsieurNicolas**

### CODE REVIEW

**Comment by istrau2** [comment]
I am not sure where we are supposed to be commenting on this but I think that the fee calculation is somewhat misleading. Effectively, there is no "fee", there are only suggested fees depending on what you want to accomplish similar to this: https://web3js.readthedocs.io/en/1.0/web3-eth.html#getgasprice

Perhaps there should be a calculation where one could provide parameter on what they were trying to accomplish (i.e. speed vs affordability)? This should obviously be an endpoint in horizon as well.

**Comment by MonsieurNicolas** [comment]
@istrau2 you should comment in one of the issues linked from the CAP, we're trying to avoid having feedback all over the place

**Comment by istrau2** [comment]
@MonsieurNicolas I am not seeing any links. Where are these links you mention?

**Comment by MonsieurNicolas** [comment]
each CAP has a "discussion" field in the header. For this one, it's:
Discussion: https://github.com/stellar/stellar-protocol/issues/75
https://github.com/stellar/stellar-protocol/issues/133

**Pull request merged**
