### PR TITLE
Mark `dest` as optional in SEP-0006 withdraw

### PR DESCRIPTION
**Pull request by jimdanz**
If an anchor is requiring interactive customer information, it may be possible to omit `dest` in the initial withdraw API call.  The reason being that the anchor can collect the dest information interactively while they collect the customer information.

I would propose that anchors that want to declare that dest is required should do so via the Info endpoint.

### CODE REVIEW

**Comment by accordeiro** [comment]
Hi @jimdanz – your reasoning makes sense, as long as that information is gathered interactively. 

Could you also update the [Info Example](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0006.md#response-2) to illustrate how an anchor server could inform that `dest` is optional or required?

**Comment by theaeolianmachine** [comment]
Hey @jimdanz, did you see @accordeiro's comment? Anything you need from us for you to add the example? Would love to get this merged in.

**Comment by accordeiro** [comment]
@tomquisel & @theaeolianmachine I've just pushed an example for the `/info` endpoint. I think it makes sense to add the `optional` flag here because on upstream/master this asset's withdrawal is `authentication_required`, as in:

https://github.com/stellar/stellar-protocol/blob/edcbbd825188c83c47c3c7272f54fe7b3d1eaf00/ecosystem/sep-0006.md#L406-L409

Let me know your thoughts.

**Comment by theaeolianmachine** [comment]
Merging this in given @tomquisel's approval

**Pull request merged**
