### PR TITLE
sep-0002.md fixes

### PR DESCRIPTION
**Pull request by jedmccaleb**
This is only one direction. Ideally this protocol would handle both depositing and withdrawing.

It seems like there needs to be more structure around what wallets do with the info that is returned. 

Is anything dynamic here? Why not just shove it in the stellar.toml ?

### CODE REVIEW

**Comment by jedmccaleb** [comment]
I feel like this is only useful for digital currencies.  How would it be used for traditional anchors?

There is the whole "forward" concept in federation now which is "withdrawal" in this context but I'm not sure how you make wallets handle it programmaticly. 
Maybe this whole thing is actually just another type of federation. 

`type=anchor&q=<stellar account>`

returns something like:
```
{
   "deposit_addr" : <other protocol address to send to>,
   "deposit_msg : "some text to display to the user",
   "withdraw_msg": "some text to display to the user"    
}
```
I feel like for crypto withdrawal it should be handled in the send form of the wallet. If you try to send to a BTC address the wallet automatically does the federation with your btc anchor. So you enter in the send form that you want to send to 1ANuUuBDN3VT6p7FoWYLTwas5QLoAgEnKk then the wallet in the background does 1ANuUuBDN3VT6p7FoWYLTwas5QLoAgEnKk*naobtc.com (or whatever your default anchor is)

The cool thing about this is that it allows you to send to BTC addresses without you holding BTC or even trusting a BTC anchor in Stellar.

**Comment by tempofr** [comment]
I agree... we could just extend the federation request.
type=query,
asset=EURT
lang=en
```result = [{
"lang": "en",
"countries: "AM",
"cost": "1%",
"time": "35 minutes",
"description": "Cash pickup at all major banks in Armenia via Unistream Bank for more info https://t.go/xxxx"},
{"countries: "RU",
"lang": "en",
"cost": "0.8%",
"time": "15 minutes",
"description": "Cash pickup at all 1000 banks in russia via Unistream Bank for more information https://t.go/xxxx"}]
```
Or it could be simply json files in the .well-known directory
something like 
eurt_en_payout.json

**Comment by bartekn** [comment]
Federation protocol was designed to map memo attached to transaction to information about recipient/destination (username, bank account, etc.). I don't see how idea explained in this SEP is related to federation concept. It just returns some static information about deposits, it does not route anything to memo.

I think the best place for this would be in stellar.toml as it gives more information about assets issued by a given FI/domain and this data is already in stellar.toml. For argument that this data is can change from time to time, it's not a problem to generate stellar.toml file in a backend. It doesn't have to be a static file on a server.

**Comment by seancil** [comment]
I like the idea of this being an extension of federation, with much of the information discovery occurring via the stellar.toml.

I would like to see more information in the stellar.toml for each forward 'type', e.g.

```
[[forward]]
type="phone"
label="Send USD to any US mobile phone number"
minAmount="2.00"
maxAmount="1000.00"

[[forward.fields]]
name="recipient"
label="Recipient Mobile"
hint="Mobile number with country code (e.g. +1 123 5678 9101)"
type="text"
required=true

[[forward.fields]]
name="fullName"
label="Recipient Name"
hint="Recipient's full name"
type="text"
```

I could then use the 'phone' forward:

`/federation?type=forward&forward_type=phone&asset=USD&amount=100.00&recipient=%2B61412345678&fullName=Bob+Smith`

returning a time-limited 'quote' confirming the information I sent + giving me my choices for what asset (w/ assoc. amount) to send.

```
{
	"forward": {
		"asset_code": "USD",
		"amount": "100.00"
	},
	"forward_fields": {
		"recipient": "+61412345678",
		"fullName": "Bob Smith"
	},
	"send_address": <stellar address>,
	"memo_type": <memo_type>,
	"memo": <memo>,
	"send": [
		{
			"asset_code": "USD",
			"asset_issuer": <free anchor issuing address>
			"amount": "100.00"
		},
		{
			"asset_code": "USD",
			"asset_issuer": <expensive anchor issuing address>
			"amount": "104.50"
		}
	],
	"expires": 1508654727
}
```

To deposit into a Stellar account, we may not need to publish as much information in the stellar.toml, and return user-facing info inside the quote:

```
[[deposit]]
type="bpay"
label="Deposit AUD using BPAY"
minAmount="2.00"
```

Wallet request:

`/federation?type=deposit&deposit_type=bpay&deposit_address=<stellar_address>&asset=AUD&amount=500.00`

federation response:

```
{
	"deposit_address": <stellar address>,
	"deposit_info": [
		{ "name": "Biller code", value: "AUS-ANCHOR-001" },
		{ "name": "Reference",  value: "015 051 2775 9931" },
		{ "name": "Instructions",  value: "Deposit to your Stellar account using BPAY. Deposits will take 24-48 hours to appear in your account." },
	],
	"deposit": {
		"asset_code": "AUD",
		"amount": "500.00"
	},
	"send": [
		{
			"asset_code": "AUD"
			"amount": "505.00"
		}
	],
	"expires": 1508654727
}
```

This would be sufficient to process an AUD deposit via any Australian bank (ignoring KYC).

I think it's important to handle fees through this protocol, and having 'quotes' ensures that the payment processors/anchors can have whatever exotic pricing they might require.

I don't necessarily like the 'deposit' type here with the opposite being 'forward'. I would be tempted to go with forward vs. receive.

**Comment by nikhilsaraf** [comment]
The concept of federation seems more like DNS: resolving between friendly names on the federation server and stellar account IDs.

So using the concept of `forward` in federation to support `deposits` and `withdrawals` seems like it could cause some confusion. I feel like deposits and withdrawals may be out of scope of federation and the use cases of deposits and withdrawals are large enough to warrant their own server and API. This will keep the concepts of `deposit` and `withdrawal` separated out from `federation`, and will allow us to bake in some basic logic of handling deposits and withdrawals from common paths (`BTC`, `ETH`, etc.). We could also include some version of `bifrost` into our prebuilt implementation of this new server.

**This new server should be solely responsible for managing the exchange of assets/currencies between the Stellar Network and external networks (or fiat currencies).**

It is akin to buying tokens to be used on the Stellar Network, and so I'm using the name `tokenization` server as a placeholder _(not the best name so please suggest another one!)_. We can use the `stellar.toml` to configure this new `tokenization` server to return values in accordance to the API below.

I’ve put together a proposal for use cases that this `tokenization` server should cover along with a sample API. It takes into account all the cases mentioned above so should not be too far off. **This is just a first draft, so please share your thoughts and comments.**


## Use cases
1. **Deposit**
    1. **Query**: Get currencies that can be deposited with this anchor and the Assets that will be issued in exchange on the Stellar Network
    2. **Prepare**: Send non-XLM currency to anchor and anchor credits the stellar account with Lumens or the same unit of non-XLM currency
2. **Withdraw**
    1. **Query**: Get Assets that can be sent to this anchor via the Stellar Network to be withdrawn out of the Stellar Network
    2. **Prepare**: Withdraw lumens or non-XLM currency out of the Stellar Network into another currency (same currency in the case of non-XLM withdrawals)


## API for 1-i (Deposit Query)
    Method: GET
    Endpoint: /deposit/query
    Description: Returns list of available options for deposit; does not require guarantee of quoted rates
    Request: object <{    // these are filters
        type (optional): string <bitcoin,ethereum,wire,ach,etc.>,
        currency (optional): string <BTC,ETH,USD,INR,etc.>,
        assetCode (optional): string <BTC>,
        assetIssuers (optional): list of strings <[GA..., GD..., etc.]>        // this allows you to filter the asset issuers to only be the ones you trust
    }>
    Response: object <{
        options: list <[{
            type: string <bitcoin,ethereum,wire,ach,etc.>,
            currency: string <BTC,ETH,USD,INR,etc.>,
            asset: object <{type, code, issuer}>,
            rate: object <{ n, d }>,    // units of currency needed to buy one unit of Asset; this includes any fees or discounts levied by the anchor
            eta: string <3-5 days, etc.>,
            minAmount (optional): number <1,2,0.5,etc.>,    // refers to units of currency
            maxAmount (optional): number <1,2,0.5,etc.>,    // refers to units of currency
            additionalParams (optional): object <{}>,    // any additional data needed as an input for this deposit, example: Bank Name
        }]>
    }>
    Errors: TBD
    Example:
        Request: {}    // an empty request is valid
        Response: {
            options: [{
                type: “wire”,
                currency: “INR”,
                asset: { type: “credit_alphanum_4”, code: “INR”, issuer: “G…” },
                rate: { n : 1035, d: 1000 },    // 3.5% fee
                eta: “5 business days”,
                minAmount: 100,
                maxAmount: 100000,
                additionalParams: {
                    accountHolderName: “Name of the Account Holder”,
                    accountHolderAddress: “Address of the Account Holder”,
                    branchNumber: “The number of the bank’s branch”,
                    branchAddress: “Address of the bank’s branch”,
                    swiftCode: “Ask your bank for this code”,
                    routingNumber: “Ask your bank for this code”
                }
            }, {
                type: “ach”,
                currency: “USD”,
                asset: { type: “credit_alphanum_4”, code: “USD”, issuer: “G…” },
                rate: { n : 102, d: 100 },    // 2% fee
                eta: “2 business days”,
                minAmount: 50,
                maxAmount: 1000,
                additionalParams: {
                    bankName: “Name of your bank”,
                    routingNumber: “Ask your bank for this code”,
                    amount: “Amount you want to send, actual fee will be based on this”    // note that this option has an amount-based fee structure
                }
            }, {
                type: “bitcoin”,
                currency: “BTC”,
                asset: { type: “credit_alphanum_4”, code: “BTC”, issuer: “GA…” },
                rate: { n : 1, d: 1 },
                eta: “1-6 hours”,
                maxAmount: 50    // no minimum specified
            }, {
                type: “bitcoin”,
                currency: “BTC”,
                asset: { type: “credit_alphanum_4”, code: “BTC”, issuer: “GD…” },    // note the issuer is different from the one above (anchor != issuer is ok)
                rate: { n : 1000001, d: 1000000 }, // 0.0001% fee
                eta: “1-6 hours”,
                minAmount: 5,
                maxAmount: 5000
            }, {
                type: “bitcoin”,
                currency: “BTC”,
                asset: { type: “native”, code: “”, issuer: “” },    // note that this is issuing lumens in exchange for BTC
                rate: { n : 601, d: 100000000 }, // converts at 601 satoshis per lumen
                eta: “1-6 hours”,
                minAmount: 0.002,
                maxAmount: 100
            }]
        }


## API for 1-ii (Deposit Prepare)
    Method: POST
    Endpoint: /deposit/prepare
    Description: Caller is preparing the Anchor to receive a deposit; If the anchor returns a successful response then it should have already made the necessary state changes on it’s end to support the deposit (i.e. creation of addresses and activated it’s listeners).
    Request: object <{
        type: string <bitcoin,ethereum,wire,ach,etc.>,
        currency: string <BTC,ETH,USD,INR,etc.>,
        asset: object <{type, code, issuer}>,
        userStellarAccount: string <stellar_account_id>,
        receiveMemo (optional): string <memo_that_anchor_should_use_when_depositing_into_stellar_account>,    // to support deposits into accounts that use federation
        additionalParams (optional): object <{}>    // uses any additional params as was specified in the response from the /deposit/query endpoint
    }>
    Response: object <{
        anchorDepositAccount: string <anchor_account_id_where_to_send_currency>,
        rate: object <{ n, d }>,    // units of currency needed to buy one unit of Asset; this includes any fees or discounts levied by the anchor
        minAmount (optional): number <1,2,0.5,etc.>,    // refers to units of currency
        maxAmount (optional): number <1,2,0.5,etc.>,    // refers to units of currency
        anchorMemo (optional): string <memo_to_use_when_making_the_deposit_to_anchor>,    // in case the anchor wants you to provide a memo when sending them the deposit
        expires: date <2017-12-31T14:59:59Z>    // time until this deposit offer is valid, including guarantee of rate
    }>
    Errors: TBD
    Example1:    // example of getting USD on Stellar by depositing via ACH transfer to anchor
        Request: {    
            type: “ach”,
            currency: “USD”,
            asset: { type: “credit_alphanum_4”, code: “USD”, issuer: “G…” },
            userStellarAccount: “G...”,
            receiveMemo: “john1@mydomain.com”,
            additionalParams: {
                bankName: “Chase Bank”,
                routingNumber: “123456789”,
                amount: 1200            // we pass in the amount since it is requested based on what we got from the /deposit/query example above
            }
        }
        Response: {
            anchorDepositAccount: “4875028389”,
            rate: { 1200, 1183 },    // charged a fee of $5 + 1% = $17, i.e. $1200 buys you $1183 on the network
            minAmount: 1200,
            maxAmount: 1200,
            anchorMemo: “For Stellar Account”,
            expires: 2017-10-27T17:00:00Z
        }
    Example2:    // example of depositing BTC and receiving native lumens
        Request: {    
            type: “bitcoin”,
            currency: “BTC”,
            asset: { type: “native”, code: “”, issuer: “” },
            userStellarAccount: “G...”
        }
        Response: {
            anchorDepositAccount: “1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2”,
            rate: { n : 601, d: 100000000 }, // converts at 601 satoshis per lumen
            expires: 2017-10-27T17:00:00Z
        }


### API for 2-i (Withdraw Query)
    Method: GET
    Endpoint: /withdraw/query
    Description: Returns list of available options for withdrawals; does not require guarantee of quoted rates
    Request: object <{    // these are filters
        type (optional): string <bitcoin,ethereum,wire,ach,etc.>,
        currency (optional): string <BTC,ETH,USD,INR,etc.>,
        assetCode (optional): string <BTC>,
        assetIssuers (optional): list of strings <[GA..., GD..., etc.]>
    }>
    Response: object <{
        options: list <[{
            type: string <bitcoin,ethereum,wire,ach,etc.>,
            currency: string <BTC,ETH,USD,INR,etc.>,
            asset: object <{type, code, issuer}>,
            rate: object <{ n, d }>,    // units of currency received per unit of Asset; this includes any fees or discounts levied by the anchor
            minAmount (optional): number <1,2,0.5,etc.>,    // refers to units of currency
            maxAmount (optional): number <1,2,0.5,etc.>,    // refers to units of currency
            additionalParams (optional): object <{}>,    // any additional data needed as an input for this withdrawal, example: Bank Name
        }]>
    }>
    Errors: TBD
    // Examples can be deduced from the ones for deposit above


## API for 2-ii (Withdraw Prepare)
    Method: POST
    Endpoint: /withdraw/prepare
    Description: Caller is preparing the Anchor to receive a withdrawal from the Stellar Network; If the anchor returns a successful response then it should have already made the necessary state changes on it’s end to support the withdrawal (i.e. creation of addresses and activated it’s listeners).
    Request: object <{
        type: string <bitcoin,ethereum,wire,ach,etc.>,
        currency: string <BTC,ETH,USD,INR,etc.>,
        asset: object <{type, code, issuer}>,
        userStellarAccount: string <stellar_account_id>,
        userWithdrawAccount: string <account_id_to_withdraw_to>,
        // not included memo here, but it could be used to specify the memo used in making the anchor -> userWithdrawAccount transaction
        additionalParams (optional): object <{}>    // uses any additional params as was specified in the response from the /withdraw/query endpoint
    }>
    Response: object <{
        anchorStellarAccount: string <anchor’s_stellar_account_id_where_to_send_asset>,
        rate: object <{ n, d }>,    // units of currency received per unit of Asset; this includes any fees or discounts levied by the anchor
        minAmount (optional): number <1,2,0.5,etc.>,    // refers to units of currency
        maxAmount (optional): number <1,2,0.5,etc.>,    // refers to units of currency
        withdrawMemo (optional): string <memo_to_use_when_sending_asset_to_anchor’s_stellar_account_id>,    // to support anchors that use federation for withdrawals
        expires: date <2017-12-31T14:59:59Z>    // time until this withdrawal offer is valid, including guarantee of rate
    }>
    Errors: TBD
    // Examples can be deduced from the ones for deposit above (supports case of withdrawing to BTC if you don’t hold or trust BTC)

**Comment by nikhilsaraf** [comment]
Re-design from our discussion offline, @jedmccaleb:

### Deposit

Deposits will be a new endpoint on the federation server. It will just return the accountId where we should send the currency that we specified. We will get the equivalent Asset issued by the anchor in return.

```
Method: POST
Endpoint: `/deposit`
Request: object <{
    currency: string <BTC,ETH,USD,INR,etc.>,
    account: string <stellar_account_id>,
    createNew: boolean <true/false>    // if true, anchor will create the account and convert some of the currency to 20 lumens to fund it
}>
Response: object <{
    depositAccount: string <anchor_account_id_where_to_send_currency>
}>
Example:
    Request: {
        currency: “BTC”,
        account: “GVIJLKJDLJFLKDJFKLJKDLFJLDJFLSD”,
	createNew: true
    }
    Response: {
        depositAccount: “4875028389”
    }
```

### Withdraw

Withdrawals will reuse the federation `forward` type and will return the account and memo where we should send the Asset. The implicit understanding here is that the anchor is the issuer and we are redeeming the underlying asset from them in exchange for the credit/Asset they issued to us on the network.

```
Method: POST (since the anchor will need to do a write to save the inputs/instructions we send them in this request)
Endpoint: `/federation`
Params:
- type=forward
- forward_type=<bank_account,BTC,ETH,etc.>
- acct=<account_where_you_are_sending>
- any additional params required as is specified in the stellar.toml file.
Response: <{
    account: string <anchor’s_stellar_account_id>,
    memo: string <memo_to_use>
}>
Example1: /federation?type=forward&forward_type=bank_account&swift=BOPBPHMM&acct=2382376
{
    account: “GDIIOUADJAKLJSADKLJASDLKAJDLKJALDSALKJD”,
    memo: “0938141”
}
Example2: /federation?type=forward&forward_type=BTC&acct=1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2
{
    account: “GVJELOAKLSDJSADKLJASDLKAJDLKJALDSALKJD”,
    memo: “123908”
}
```

**Comment by seancil** [comment]
How will wallets inform users of fees? Are you suggesting they gather + display that information manually/let the user find out for themselves?

'depositAccount' on /deposit doesn't afford anchors much room when trying to specify things like bank accounts with reference/routing numbers and the like...

I can understand the want for simplicity, but you're going to push the fiat anchors to create their own/extend the APIs while the crypto issuers will be fine to follow the protocol. That might be acceptable, though.

**Comment by jedmccaleb** [comment]
reorg'd and added all of this with https://github.com/stellar/stellar-protocol/pull/57

**Pull request closed without merging**
