### PR TITLE
SEP-9: add proof_of_liveness field

### PR DESCRIPTION
**Pull request by theclabs**
resolves https://github.com/stellar/stellar-protocol/issues/1322

### CODE REVIEW

**Review by ItsKylieCyrus — APPROVED** [review]

**Review by JakeUrban — APPROVED** [review]
Hey @theclabs, thanks for contributing and sorry for the delay. I think this is a great addition to the standard.

**Comment by Inatiye0911905991** [comment]
From Ethiopia

**Comment by Inatiye0911905991** [comment]
👍

**Comment by Inatiye0911905991** [comment]
> መፍትሄ #1322

sintayewgashaw4@gmail.com

**Pull request merged**
