### PR TITLE
added Transaction level signature verification (cap0002)

### PR DESCRIPTION
**Pull request by MonsieurNicolas**
first draft

discussion located here: https://github.com/stellar/stellar-core/issues/1464

### CODE REVIEW

**Comment by johansten** [comment]
Links to the document *plz*, or just redo this whole process

**Comment by bartekn** [comment]
1. "Files changed" tab.
2. "View" button.

However, maybe we can create a PR template in this repo so users add the direct link to the doc.

**Comment by vogel** [comment]
I like this proposal, it makes lots of things simpler.

**Comment by MonsieurNicolas** [comment]
per cap process, I am merging this draft; discussion should continue in related issue

**Pull request merged**
