### PR TITLE
[SEP31] Change URL end-point to create a new transactions.

### PR DESCRIPTION
**Pull request by abuiles**
This is a follow up on https://github.com/stellar/stellar-protocol/pull/692 -- the proposal is to create new transactions through a `POST` request on `/transactions`.

This PR also updates the response code to a 201, meaning a new transaction has been created and can be processed.

### CODE REVIEW

**Comment by JakeUrban** [comment]
Can we make the associated change with `PUT /update` too? It should be `PATCH /transaction`

**Comment by abuiles** [comment]
@JakeUrban that's on the other PR :)

**Comment by JakeUrban** [comment]
You're right.. nvm

**Comment by JakeUrban** [comment]
We should wait on merging this though until we get community feedback.

**Pull request merged**
