### PR TITLE
Deprecate SEP3

### PR DESCRIPTION
**Pull request by msfeldstein**
according to [our docs](https://www.stellar.org/developers/guides/compliance-protocol.html) we don't recommend sep3 usage anymore and i don't know anyone who's actually implemented it.  Deprecate it now to avoid confusion in future.

### CODE REVIEW

**Comment by leighmcculloch** [comment]
Copying over my commented from https://github.com/stellar/stellar-protocol/pull/419#issuecomment-538558468:

Does this mean the [compliance] and [bridge] servers are deprecated as well? The linked document definitely favors SEP-6/12 over SEP-3, but it also acknowledges that most cases will be better served by them, not all. What's the use case for SEP-3 that we might be missing here?

[compliance]: https://github.com/stellar/go/tree/master/services/compliance
[bridge]: https://github.com/stellar/go/tree/master/services/bridge

**Comment by msfeldstein** [comment]
Unclear why there's 2 PRs for this but some more conversation in https://github.com/stellar/stellar-protocol/pull/419

**Comment by msfeldstein** [comment]
@rice2000 @tomquisel is the reason that this was never adopted by anyone because no one had a business need for it, or because it wasn't flexible enough to serve most needs (a la non-interactive sep6)?

**Comment by tomquisel** [comment]
I think it was lack of business need, but I don't know all the history. @jedmccaleb do you know?

**Comment by tomquisel** [comment]
I was chatting with Lisa at the offsite, and she brought up how Tempo and Cowrie want to interact. Basically, they want to exchange client KYC info server-to-server, just like SEP-3 and the compliance server provide. @tomerweller and @msfeldstein maybe it's worth syncing to see if SEP-3 is the right answer and if it's worth un-deprecating SEP-3 for it? Sorry to get that thought in after the cutoff 😄

**Comment by msfeldstein** [comment]
Can you tag someone from those orgs to take a look and see if they want to use this?  If this would solve their problems i'm happy to undeprecate

**Comment by rice2000** [comment]
@tempofr Thoughts?

**Comment by tomerweller** [comment]
I think that by creatively squinting at sep24 you can mimic sep3. Essentially, you need to have the sender initiate a withdraw on behalf of the recipient before they start the deposit on their end. Only after getting the thumbs up to withdraw, they deposit and complete the withdraw using a path payment.

Obviously, wallets that support this flow would need to join the creative squinting. I still think it's better to have one deposit/withdraw standard. 

@msfeldstein thoughts?

**Comment by msfeldstein** [comment]
i would be ok with adding some color to SEP24 to make this flow more
obvious so we don't have to squint

**Comment by tomquisel** [comment]
I'm onboard for the SEP-24 B2B approach! It'd be amazing if we could use the same tooling (polaris and demo wallet) to support / test both cases.

**Pull request merged**
