### PR TITLE
Add refunded transaction status to SEP-0006

### PR DESCRIPTION
**Pull request by istrau2**
Adds a refunded transaction status.

### CODE REVIEW

**Comment by istrau2** [comment]
@tomquisel

**Comment by tomquisel** [comment]
I like the idea of this field, although it could lead to confusion. A deposit / withdrawal could have hit one of the other issues (like `no_market`), and then been refunded. We'd want to communicate to the user both the underlying reason for the refund `no_market` and the fact that it has been refunded. Maybe `refunded` should be a separate field?

**Comment by accordeiro** [comment]
@istrau2 any thoughts on @tomquisel's suggestion?

**Comment by istrau2** [comment]
@tomquisel @accordeiro Sounds good to me. I am ok with either approach really.

**Comment by theaeolianmachine** [comment]
@istrau2 can you make the change so we can merge this in?

**Comment by istrau2** [comment]
@theaeolianmachine sorry, done.

**Comment by theaeolianmachine** [comment]
Thank you!

**Pull request merged**
