### PR TITLE
SEP-0033: add project url of Go implementation.

### PR DESCRIPTION
**Pull request by overcat**
- add project url of [Golang implementation](https://github.com/StellarCN/stellar-identicon-go).

### CODE REVIEW

**Review by leighmcculloch — DISMISSED** [review]
👍🏻  Could you update the meta tags by adding a Version field, set it to Version 1.0.1, and an Updated field, set it to todays date?

cc @pitsevich

**Comment by overcat** [comment]
Hi @leighmcculloch, it is still a draft, wouldn't it be better to set the version to 0.1.1?

**Comment by leighmcculloch** [comment]
The status and the version are independent. @pitsevich Do you have a preference on what version the current version be assigned?

**Comment by leighmcculloch** [comment]
Actually I think this SEP should be in Active status. I've opened a PR proposing that and why. If we can merge that first this PR can slide in after it: https://github.com/stellar/stellar-protocol/pull/891/files

**Comment by overcat** [comment]
Of course, I will update this PR after you merge #891.

Leigh McCulloch ***@***.***> 于 2021年3月16日周二 上午12:57写道：

**Comment by pitsevich** [comment]
@leighmcculloch @overcat my apologies for not getting back to you earlier. 

Excited to see a Go implementation - that’s awesome.
Sure, let’s move to active and this would mark a 1.0.1

**Review by leighmcculloch — APPROVED** [review]

**Pull request merged**
