### PR TITLE
Draft of cap-0006

### LINKED ISSUE #180: Allow buy offers
Currently, stellar only allows for sell offers. However, translating buy offers to sell offers does not preserve the intent of the trader. 

Quoting @ScottHogge from the stellar's keybase team: 
> Lets say you want to buy exactly 10 Marbles for at most $1 each... if you re-frame this as an offer to sell $10 at a price of 1 Marble/$,  you could end up getting 20 Marbles at $0.5 if the orderbook contains an offer to sell Marbles at $0.5 --while the desired effect would be just 10 Marbles at $0.5.  This behavior is different than in any traditional market (stocks, options, futures, etc...) and is kinda problematic for the financial industry adopting SDEX usage when they have a duty to execute customer orders as directed.

### PR DESCRIPTION
**Pull request by jonjove**
#180

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
removed the "resolves" as this is a draft

**Comment by MonsieurNicolas** [comment]
merging, so that we continue discussing in #180

**Comment by skirsch** [comment]
This is awesome. This is one of the two major "mis-features" of Stellar, and this addresses it. THANK YOU. The other mis-feature on my list is inability to send someone my USD directly. there should be a flag on an account to enable this.

**Comment by theaeolianmachine** [comment]
@skirsch - are you discussing the need for someone to establish a trustline before sending them a token, or something else? Is there another issue in this repo already addressing what you're talking about?

**Comment by skirsch** [comment]
@theaeolianmachine yes, there is another issue on the "how can I send someone my USD" (since they don't have a trustline) problem: https://github.com/stellar/stellar-protocol/issues/188

Is that what you were asking?

**Comment by theaeolianmachine** [comment]
Yes, that's correct - wanted to make sure it was that issue. We're actively looking at several proposals, including SEP-0013 & CAP-0007, along with a few others that haven't been drafted yet.

**Comment by skirsch** [comment]
Great. fixing the how can I send my token problem is I think one of the reasons ripple failed. it's awkward today as you know.

**Comment by oriana13** [comment]
Hello @skirsch,
May I ask you for your solution regarding the trust line? Because currently I have the same problem: I want to create a function that sends an NFT, the only problem is that the recipient does not have a trust line and when I create it in my function, I do not have the secret key of the recipient who must sign ...

**Pull request merged**
