### PR TITLE
SEP-0009: update "birth_place" field type from date to string

### PR DESCRIPTION
**Pull request by marcelosalloum**
### What

Update SEP-9 `birth_place` field type from "date" to "string".

### Why

The field description says _"Place of birth (city, state, country; as on passport)"_ so I'm assuming its type should actually be "string".

### CODE REVIEW

**Comment by marcelosalloum** [comment]
Please let me know if this fix should trigger a version bump from `1.3.1` to `1.3.2`

**Comment by JakeUrban** [comment]
Thanks for catching this @marcelosalloum , lets bump the patch version and I'll approve 👍

**Comment by marcelosalloum** [comment]
> lets bump the patch version and I'll approve 👍

Done 😄

**Review by JakeUrban — APPROVED** [review]

**Review by leighmcculloch — APPROVED** [review]
Nice catch. :shipit:

**Pull request merged**
