### PR TITLE
cap-0023 - Change OperationID to a union

### PR DESCRIPTION
**Pull request by sisuresh**

### CODE REVIEW

**Comment by abuiles** [comment]
@sisuresh I was looking at CAP0023 and noticed this change -- could you add a comment on the PR description on why this is changing? Is it related with other CAP?

**Comment by sisuresh** [comment]
@abuiles I added a description. It’s a minor change to keep the user from using `OperationID` with the wrong envelope type. The `OperationID` will be used as a hash pre-image for the `ClaimableBalanceID`, so this shouldn’t affect anything outside of stellar-core right now.

**Comment by ire-and-curses** [comment]
@sisuresh thanks for adding the comment! As part of approving these CAPs, we're tasked with looking at every line of XDR to understand the downstream implications. So even if something doesn't seem likely to impact downstream, we appreciate the description and rationale. In this case any change to the CAP is of interest as Adolfo and I are part of the working group for the CAP.

**Comment by sisuresh** [comment]
@ire-and-curses No problem! I'll make sure to include descriptions going forward.

**Pull request merged**
