### PR TITLE
CAP-0048 Smart Contract Asset Interoperability: First draft

### PR DESCRIPTION
**Pull request by jonjove**

### CODE REVIEW

**Review by MonsieurNicolas — APPROVED** [review]

**Comment by leighmcculloch** [comment]
This PR was merged with an invalid diff. @jonjove Can you fix the diff?

**Comment by leighmcculloch** [comment]
I'm updating the repo config to require the builds pass: https://github.com/stellar/terraform/pull/791.

**Comment by jonjove** [comment]
@leighmcculloch yes, noticed that too. Will fix now and add it to #1190.

**Comment by leighmcculloch** [comment]
@jonjove pointed out this failure can't be resolved because the correct commit to use on the diff is on a pull request, and pull requests are not included in the default git fetch that mddiffcheck does.

I've opened a change to mddiffcheck that will add the ability for us to reference commits in pull requests. It is here: https://github.com/stellar/mddiffcheck/pull/6. Once it is merged @jonjove's fix should resolve it.

**Pull request merged**
